[package]
name = "daw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-as-inner = "0.5.1"
byteorder = "1.4.3"
method_shorthands = "0.2.0"